title: Anggit Nila Waska Della # your name (or website title) here
logo: "/images/profil.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>I'm a fourth year college student at Gunadarma University with major System Information who starting to look for roles in the data science. I've been focused on getting good grades throughout my school years. Which resulted in me getting my best on my final score. By joining several courses, I 've been well equipped by Database, Data visualization, Critical thinking, team work. thus, it helps me a lot in running an event called courses where i became the analys or scientist and have a responsibility to work. I have a deep interest in learn in learning about Data Science and being part of organizations to impact society. I'm a learner and welcome any recommendations on things to do that challenge me always to have a growth mindset.<br>
 
  <a href="https://www.linkedin.com/in/anggitnila/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

